services:
  app:
    build: .
    container_name: vs-app
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-vs.entrypoints=websecure
      - traefik.http.routers.app-vs.rule=Host(`veyvy.space`)
      - traefik.http.routers.app-vs.tls.certresolver=letsencryptresolver
      - traefik.http.routers.app-vs.service=app-vs_svc
      - traefik.http.services.app-vs_svc.loadbalancer.server.port=3000
      - traefik.docker.network=web

networks:
  web:
    external: true
